name: scale-in-azure
on:
  repository_dispatch:
    types: 
      - scale-in-azure

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: output webhook payload
      run: echo "The source of the webhook is = ${{ github.event.client_payload }}"
    

    - name: parse client payload data for scaling
      id: client_payload_data
      run: |
        echo ::set-output name=student_nbr::${{ github.event.client_payload.studentNbr }}
    
    - name: output student number
      run: echo "This is the student number ${{ steps.client_payload_data.outputs.student_nbr }}"

    - name: install consul client
      run: sudo sh scripts/consul.sh

    - name: get consul server parameters
      id: consul_params
      run: echo ::set-output name=consul_server::$(cat configs/consul_server.cfg)

    - name: query bigip scaling min/max values
      id: bigip_scaling
      run: |
        echo ::set-output name=bigip_min::$(consul kv get -http-addr=${{ steps.consul_params.outputs.consul_server }} adpm/labs/agility/common/scaling/bigip/min)
        echo ::set-output name=bigip_max::$(consul kv get -http-addr=${{ steps.consul_params.outputs.consul_server }} adpm/labs/agility/common/scaling/bigip/max)

    - name: output min and max values
      run: |
        echo "This is BIG-IP minimum scaling value = ${{ steps.bigip_scaling.outputs.bigip_min }}"
        echo "This is BIG-IP maximum scaling value = ${{ steps.bigip_scaling.outputs.bigip_max }}"

    - name: query student data
      id: student_data
      run: echo ::set-output name=bigip_instance_count::$(consul kv get -http-addr=${{ steps.consul_params.outputs.consul_server }} adpm/labs/agility/students/${{ steps.client_payload_data.outputs.student_nbr }}/scaling/bigip/current_count)

    - name: output student data
      run: echo "The current BIG-IP instance count for student ${{ steps.client_payload_data.outputs.student_nbr }} is ${{ steps.student_data.outputs.bigip_instance_count }}"

    - name: check if can scale in
      id: check_scale
      run: echo ::set-output name=desired_capacity::$(expr ${{ steps.student_data.outputs.bigip_instance_count }} - 1)

    - name: scale in
      if: steps.check_scale.outputs.desired_capacity > 0
      run: echo "CAN scale in..."
    
    - name: can't scale
      if: steps.check_scale.outputs.desired_capacity <= 0
      run: echo "CANNOT scale in..."