name: workflow router
on: 
  repository_dispatch:
    types:
      - wf_router
jobs: 
  
  setup:
    env:
      CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
    runs-on: ubuntu-latest
    steps:
    - name: dump client payload
      id: payload
      run: |
        echo "client payload = ${{ github.event.client_payload.scaling_type }}"
        
    - name: setup
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.WF_ROUTER_PAT }}

    # - name: write payload
    #   run: |
    #     echo "${{ env.CLIENT_PAYLOAD }}" > client.txt

    # - name: read payload
    #   run: |
    #     cat client.txt
 #       cat client.txt | sed s/{/\'{/
    
    - name: check if exists 
      id: file
      run: |
        if [ ! -f ./.github/workflows/student-${{ github.event.client_payload.student_id }}.yaml ]; then
          echo ::set-output name=file_exists::"false"
        else
          echo ::set-output name=file_exists::"true"
        fi

    - name: get date
      id: get_date
      run: echo ::set-output name=date_time::$(date +'+%Y-%m-%d %H:%M:%S')

    - name: render workflow
      run: |
        with:
        cat .github/workflows/scale-azure-2.tpl | sed ' s/WORKFLOW_NAME/student-${{ github.event.client_payload.student_id}}/; s/DDATE/${{ steps.get_date.outputs.date_time }} ' > .github/workflows/student-${{ github.event.client_payload.student_id}}.yaml

    - name: cat yaml
      run: cat .github/workflows/student-${{ github.event.client_payload.student_id }}.yaml

    - name: commit changes
      if: ${{ steps.file.outputs.file_exists == 'false' }}
      run: |
          git add .github/workflows/student-${{ github.event.client_payload.student_id }}.yaml
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git commit -m "changed" -a
          git push 
          echo "COMMITTING"

    - name: invoke webhook
      run: |
        declare -a command=(curl -H "Authorization: token ${{ secrets.WF_ROUTER_PAT }}" --request POST --data '{"event_type": "student-${{ github.event.client_payload.student_id }}", "client_payload": ${{ env.CLIENT_PAYLOAD}}}' https://api.github.com/repos/f5businessdevelopment/adpm-agility/dispatches)
        "${command[@]}"
        